In [1]:
%cd /home/q123/Desktop/explo
from src.policy import MLP
from src.environment import EnvironmentObjective

import torch
import gym

/home/q123/Desktop/explo


/home/q123/miniconda3/envs/explo/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from torch.linalg import norm
mlp = MLP([3,1])

# Initialize environment

objective_env = EnvironmentObjective(
  env=gym.make("Pendulum-v1"),
  policy=mlp,
  manipulate_state=None,
  manipulate_reward=None,
)
states = objective_env.get_grid()

### initialize train_x, train_y
train_x = torch.rand(1,100,mlp.len_params) ## [n_trials,n_params]
test_x = torch.rand(1,1,mlp.len_params) ## acquisition point

#params_batch = torch.hstack([train_x,test_x])
params_batch = test_x
A  = [norm(mlp(states,p))
                for p in params_batch.flatten(end_dim=-2)
                ]

gradient = torch.autograd.grad(outputs=A[0], inputs=test_x)

In [125]:
states = torch.rand(1,3,requires_grad=False)
net = torch.nn.Linear(3,1)
test_x = torch.ones(3,1,requires_grad=True)
net.weight.data = torch.nn.Parameter(test_x.T)

A =torch.sum(net(states))
gradient = torch.autograd.grad(outputs=A,inputs=net.parameters())
print(gradient)
# print(states)

(tensor([[0.5545, 0.2673, 0.4952]]), tensor([1.]))


In [126]:
states = torch.rand(1,3,requires_grad=False)
net = torch.nn.Linear(3,1)
test_x = torch.ones(3,1,requires_grad=True)
net.weight.data = test_x.T
#############################

A =torch.sum(net(states))
gradient = torch.autograd.grad(outputs=A,inputs=test_x,allow_unused=True)
print(gradient)
# print(states)

(None,)


In [ ]:
MLP(torch.nn.Module):
    def __init__(self,parameters):
        
        self.net = 
        
        
    def forward()

In [ ]:
from torch.nn import Function

MLP(Function):
    
    @staticmethod
    def forward(ctx,input,params):
        ctx.save_for_backward(ctx,input,params)
        output = self.net(params)
        
        
    
    @staticmethod
    def backward(ctx,input,params):
        
        

In [129]:
states = torch.rand(1,3,requires_grad=False)
net = torch.nn.Linear(3,1)
test_x = torch.ones(3,1,requires_grad=True)
net.weight.data = torch.nn.Parameter(test_x.T)
#############################

A =torch.sum(net(states))
gradient = torch.autograd.grad(outputs=A,inputs=test_x)
print(gradient)
print(states)

RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

In [62]:
states = torch.rand(1,3,requires_grad=False)
net = torch.rand(3,1,requires_grad=True)
A = torch.sum(states@net)
gradient = torch.autograd.grad(outputs=A,inputs=net)
print(gradient)
print(states)

(tensor([[0.1829],
        [0.9422],
        [0.8886]]),)
tensor([[0.1829, 0.9422, 0.8886]])


In [132]:
states = torch.rand(1,3,requires_grad=False)
a = torch.ones(1,1,19,requires_grad=True)
mini_a = a[:,:,:9].reshape(a.shape[:-1]+(3,3))
mini_b = a[:,:,9:18].reshape(a.shape[:-1]+(3,3))
A = torch.sum(mini_b@mini_a@states.T)
gradient = torch.autograd.grad(outputs=A,inputs=a)
gradient[0].shape
print(gradient)

(tensor([[[0.8859, 2.6932, 1.9828, 0.8859, 2.6932, 1.9828, 0.8859, 2.6932,
          1.9828, 1.8540, 1.8540, 1.8540, 1.8540, 1.8540, 1.8540, 1.8540,
          1.8540, 1.8540, 0.0000]]]),)
