In [1]:
%cd /home/q123/Desktop/explo

import torch 
import gpytorch 
import logging
import logging.config

from src.helpers import setup_experiment
from src.trainer import Trainer
from src.optimizers.gibo import GIBOptimizer
from src.optimizers.vanilla_bo import BOptimizer
from src.config import get_configs

logging.config.fileConfig('logging.conf')
# create root logger
logger = logging.getLogger()
print("hello")


/home/q123/Desktop/explo


/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/gym/envs/registration.py:415: UserWarning: WARN: The `registry.env_specs` property along with `EnvSpecTree` is deprecated. Please use `registry` directly as a dictionary instead.
  logger.warn(
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
pybullet build time: Jun 23 2022 12:25:14


hello


In [2]:
seed = 110

#env_name = "CartPole-v1" ## Action kernel + State_norm looks very well for cartpole
env_name = "Swimmer-v4" ##  State_norm stabilizes training 
#env_name = "Hopper-v2"
kernel_name = "rbfstate" ## "linearstate" /"rbfstate"

env_config,likelihood_config,kernel_config,optimizer_config,trainer_config = get_configs(env_name,kernel_name)

optimizer_config = {
        "n_eval":2, ## 3 for cartpole (very noisy)
        ### for GIBO
        "n_max":32, 
        "n_info_samples":16,
        "delta":0.1, ## 0.01 for cartpole
        ### hessian normalisation applies only for rbf
        "normalize_gradient": True,
        "standard_deviation_scaling":False,
}


likelihood_config = {
                "noise_hyperprior":gpytorch.priors.torch_priors.UniformPrior(a=0.01,b=0.05),
                "noise_constraint":gpytorch.constraints.constraints.Interval(0.01,0.05)
                }


kernel_config = {
        "use_ard":True,
        "kernel_name":kernel_name,
        #"lengthscale_hyperprior":gpytorch.priors.torch_priors.GammaPrior(2,0.2),
        #"lengthscale_hyperprior":gpytorch.priors.torch_priors.NormalPrior(1,0,),
        "lengthscale_constraint":gpytorch.constraints.constraints.Interval(0.1,10),
        #"outputscale_hyperprior":gpytorch.priors.torch_priors.GammaPrior(2,0.4),
        "outputscale_constraint":gpytorch.constraints.constraints.GreaterThan(0.01),
        }

policy_config = {
        "add_layer":[],### can be empty or [8,7] for adding 2 layers with width 8,7  neurons respectively
        "add_bias":False,
}

trainer_config = {
        "n_steps":100, 
        "report_freq":10,
        "save_best":False,
        "wandb_logger":True,
        "run_name" : env_name+kernel_name+str(seed)+"a",
        "wandb_config": {**optimizer_config,**likelihood_config,**kernel_config,**policy_config}
}


model,objective_env = setup_experiment(env_config,kernel_config,likelihood_config,policy_config,
                                       seed=seed)


### Chose optimizer 
#optimizer = BOptimizer(**optimizer_config)
optimizer = GIBOptimizer(model,**optimizer_config)
trainer = Trainer(model,objective_env,optimizer,**trainer_config)
rslt= trainer.run()

### ADD LR SCHEDULAR  / FIX DISCRETIZATION ===> ENJOY WEEKEND :DDD

MathLog.src.helpers : WARNING : MLP dimensions : [8, 2]
Using state normalization
MyRBF received 16000 use_ard True
fixing seed to  110
 Gibo will use 32 last points to fit GP and 16 info samples


/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/notebook/utils.py:280: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return LooseVersion(v) >= LooseVersion(check)
wandb: Currently logged in as: mahdikallel. Use `wandb login --relogin` to force relogin
/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py:47: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML  # type: ignore


MyRBF received 4000 use_ard True


/home/q123/miniconda3/envs/boptim/lib/python3.10/site-packages/gpytorch/lazy/lazy_tensor.py:1741: UserWarning: torch.triangular_solve is deprecated in favor of torch.linalg.solve_triangularand will be removed in a future PyTorch release.
torch.linalg.solve_triangular has its arguments reversed and does not return a copy of one of the inputs.
X = torch.triangular_solve(B, A).solution
should be replaced with
X = torch.linalg.solve_triangular(A, B). (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:1672.)
  Linv = torch.triangular_solve(Eye, L, upper=False).solution


acq_diff tensor(0.0075) n_info 4
model mean constant Parameter containing:
tensor([0.0569], requires_grad=True)
MyRBF received 4000 use_ard True
acq_diff tensor(0.0002) n_info 3
model mean constant Parameter containing:
tensor([-0.0589], requires_grad=True)
MyRBF received 4000 use_ard True
model mean constant Parameter containing:
tensor([0.0065], requires_grad=True)
MyRBF received 4000 use_ard True
model mean constant Parameter containing:
tensor([0.0096], requires_grad=True)
MyRBF received 4000 use_ard True
acq_diff tensor(3.1734e-05) n_info 3
model mean constant Parameter containing:
tensor([0.0590], requires_grad=True)
MyRBF received 4000 use_ard True
acq_diff tensor(2.8298e-05) n_info 3
model mean constant Parameter containing:
tensor([0.1135], requires_grad=True)
MyRBF received 4000 use_ard True
acq_diff tensor(3.5030e-05) n_info 3
model mean constant Parameter containing:
tensor([0.0977], requires_grad=True)
MyRBF received 4000 use_ard True
acq_diff tensor(0.0016) n_info 3
model

KeyboardInterrupt: 

In [ ]:
import scipy.stats as stats 
import numpy as np
import matplotlib.pyplot as plt

alpha = 2
beta = 0.3
x = np.linspace (0, 10, 200) 
y1 = stats.gamma.pdf(x, a=alpha, scale=1/beta)
plt.plot(x,y1)