In [ ]:
%cd /home/mkallel/explo/

import torch 
import numpy as np
import gpytorch 
import logging
import logging.config

from src.helpers import setup_experiment
from src.trainer import Trainer
from src.config import get_configs


logging.config.fileConfig('logging.conf')
# create root logger
logger = logging.getLogger()
print("hello")

from warnings import simplefilter 
simplefilter(action='ignore', category=DeprecationWarning)

torch.set_num_threads(1)

In [ ]:
seed = 10



torch.set_num_threads(1)

#env_name = "CartPole-v1" ## Action kernel + State_norm looks very well for cartpole
env_name = "Swimmer-v4" ##  State_norm stabilizes training 
#env_name = "Hopper-v2"
#env_name = "Walker2d-v3"


kernel_name = "rbfstate" ## "rbf"
#kernel_name = "rbf" ## "rbf"

conf_grad = False
norm_grad = True
advantage_mean = False
adaptive_lr = False

run_name = kernel_name + str(seed)+"_conf_grad"*conf_grad+"_norm_grad"*norm_grad+"_advantage"*advantage_mean
env_config,policy_config,likelihood_config,kernel_config,mean_config,optimizer_config,trainer_config = get_configs(env_name,kernel_name,
use_ard=True,manipulate_state=True,
conf_grad=conf_grad,norm_grad=norm_grad,advantage_mean=advantage_mean,adaptive_lr=False,
wandb_logger=False,run_name=run_name)

model,objective_env,optimizer = setup_experiment(env_config,mean_config,kernel_config,likelihood_config,policy_config,optimizer_config,
                        seed=seed)

trainer = Trainer(model,objective_env,optimizer,**trainer_config)
trainer.run()

### ADD LR SCHEDULAR ===> ENJOY WEEKEND :DDD



In [ ]:
a = torch.rand(1,10,100)
model.covar_module(a,a).evaluate()

In [37]:
import torch

d = 100
a = torch.rand(3,5,d)
b = torch.rand(2,5,d)
k = torch.zeros(3,2)

for i in range(d):
    k*= torch.exp(-torch.cdist(a[...,i],b[...,i])**2)

a1 = torch.flatten(a,start_dim=1)
b1 = torch.flatten(b,start_dim=1)
k1 = torch.exp(-torch.cdist(a1,b1)**2)

print((k1-k)<1e-4)



tensor([[True, True],
        [True, True],
        [True, True]])


In [4]:
import numpy as np

np.random.seed(42)
seeds = np.random.randint(low=0,high=2**30,size=(10,))
seeds

array([534895718, 199900595, 862061404, 787846414, 996406378, 127521863,
       423734972, 415968276, 670094950, 841095289])

In [27]:
print(a[...,0])
print(torch.flatten(a,start_dim=1))

tensor([[0.7451, 0.4519, 0.8520, 0.9092, 0.5902],
        [0.1724, 0.6498, 0.6940, 0.3090, 0.2608],
        [0.5382, 0.9240, 0.4726, 0.8161, 0.4965]])
tensor([[0.7451, 0.4519, 0.8520, 0.9092, 0.5902],
        [0.1724, 0.6498, 0.6940, 0.3090, 0.2608],
        [0.5382, 0.9240, 0.4726, 0.8161, 0.4965]])


In [ ]:
from multiprocessing import Pool
import wandb

n = 
seeds = np.random.randint(low=0,high=2**30,size=(n,))
seeds = [ int(i) for i in seeds]


if __name__ == '__main__':

    wandb.require("service")
    
    with Pool(processes=n) as p:
        p.map(f, seeds)

    

In [ ]:
type(seeds[0])

In [ ]:
import scipy.stats as stats 
import numpy as np
import matplotlib.pyplot as plt

alpha = 1.25
beta = 0.25
x = np.linspace (0, 10, 2000) 
y1 = stats.gamma.pdf(x, a=alpha, scale=1/beta)
plt.plot(x,y1)

In [ ]:
import torch

a = torch.rand(3,3)
a_s = a.T@a

f(a_s,m,c):

    max(f(a_s,m,c),f(a_)




def solve_qkp(a_s,c):

    f(k)






In [ ]:
f(m,w) = 

max(
    
###don't choose this item
f(m-1,w)
### choose this item
f(m-1,w-w_m)+1 
w_m = 


def f(m,w,A):



    if m == len(x) or w ==0:

        return 0